"""
    CheckedID API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""
import os
import unittest
from pprint import pprint

import checkedid
from checkedid.api import authentication_api
from checkedid.api.status_api import StatusApi  # noqa: E501
from checkedid.model.result_callback_status import ResultCallbackStatus


class TestStatusApi(unittest.TestCase):
    """StatusApi unit test stubs"""

    def setUp(self):
        self.api = StatusApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_status_get_result_callback_status(self):
        """Test case for status_get_result_callback_status

        Get result callback based on Invitation Code  # noqa: E501
        """
        configuration = checkedid.Configuration(
            host="https://api.checkedid.eu",
            api_key_prefix={"default": "bearer"},
        )

        # Enter a context with an instance of the API client
        with checkedid.ApiClient(configuration) as api_client:
            # Create an instance of the API class
            api_instance = authentication_api.AuthenticationApi(api_client)
            grant_type = "password"  # str | Should set as 'password'
            username = os.getenv(
                "CHECKEDID_USERNAME"
            )  # str | Username shared for the API access
            password = os.getenv(
                "CHECKEDID_PASSWORD"
            )  # str | Password shared for the API access

            try:
                # OAuth process to generate the authentication token
                api_response = api_instance.oauth_token_post(
                    grant_type, username, password
                )

                configuration.api_key["default"] = api_response["access_token"]

            except checkedid.ApiException as e:
                print(
                    "Exception when calling AuthenticationApi->oauth_token_post: %s\n"
                    % e
                )

        au = configuration.get_api_key_with_prefix("default")
        c = "15IMN4"
        result: ResultCallbackStatus = self.api.status_get_result_callback_status(
            invitation_code=c, authorization=au, _check_return_type=False
        )

        assert result.CustomerCode

    def test_status_get_status_v2(self):
        """Test case for status_get_status_v2

        API Status  # noqa: E501
        """
        configuration = checkedid.Configuration(
            host="https://api.checkedid.eu",
            api_key_prefix={"default": "bearer"},
        )

        # Enter a context with an instance of the API client
        with checkedid.ApiClient(configuration) as api_client:
            # Create an instance of the API class
            api_instance = authentication_api.AuthenticationApi(api_client)
            grant_type = "password"  # str | Should set as 'password'
            username = os.getenv(
                "CHECKEDID_USERNAME"
            )  # str | Username shared for the API access
            password = os.getenv(
                "CHECKEDID_PASSWORD"
            )  # str | Password shared for the API access

            try:
                # OAuth process to generate the authentication token
                api_response = api_instance.oauth_token_post(
                    grant_type, username, password
                )

                configuration.api_key["default"] = api_response["access_token"]

            except checkedid.ApiException as e:
                print(
                    "Exception when calling AuthenticationApi->oauth_token_post: %s\n"
                    % e
                )

        au = configuration.get_api_key_with_prefix("default")
        r = self.api.status_get_status_v2(
            authorization=au, _return_http_data_only=False
        )

        assert r[1] == 200


if __name__ == "__main__":
    unittest.main()
